version: '4'

services:
  web-dynasty:
    platform: linux/amd64
    image: phamvantan/web-dynasty:1.0.0
    container_name: web-dynasty
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-production

    ports:
      - 1311:1311
    networks:
      - dynasty-network

networks:
  dynasty-network:
    external: true
