version: '3.8'

services:
  web-dynasty:
    image: tanphamvan/web-dynasty:staging
    container_name: web-dynasty
    build:
      context: .
      dockerfile: Dockerfile-staging
    ports:
      - 1311:1311
    networks:
      - dynasty-network

networks:
  dynasty-network:
    external: true
